# Generated by Django 3.2.5 on 2022-11-30 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='ownerName',
            new_name='owner',
        ),
    ]
