# Generated by Django 4.1.3 on 2022-12-03 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_rename_ownername_product_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="need",
            field=models.CharField(default="hehe", max_length=100),
            preserve_default=False,
        ),
    ]
