# Generated by Django 3.2.5 on 2022-12-03 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0002_rename_ownername_product_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_code', models.CharField(max_length=32)),
                ('fullName', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=32)),
                ('address', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('comment', models.CharField(max_length=500)),
                ('attachment', models.ImageField(blank=True, upload_to='attachments/%Y/%m/%d')),
                ('customer_username', models.CharField(max_length=32)),
                ('status', models.DecimalField(decimal_places=0, default=2, max_digits=1)),
                ('id_sp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_sp', to='shop.product')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
