# Generated by Django 3.2.5 on 2022-12-03 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='id_sp',
            field=models.DecimalField(decimal_places=0, max_digits=1000),
        ),
    ]
