# Generated by Django 3.2.5 on 2022-12-03 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_alter_transaction_id_sp'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='receiver_username',
            field=models.CharField(default=None, max_length=32),
            preserve_default=False,
        ),
    ]
